

custom:
  firehose:
    name: firehose-${self:custom.stage}

    arn:
      Fn::GetAtt:
        - FirehoseStream
        - Arn

    permissions:
      read: 
        Effect: Allow
        Action:
          - 'kinesis:DescribeStream'
          - 'kinesis:GetShardIterator'
          - 'kinesis:GetRecords'
        Resource: ${self:custom.firehose.arn}

      write:
        Effect: Allow
        Action:
          - 'kinesis:DescribeStream'
          - 'kinesis:PutRecord'
          - 'kinesis:PutRecords'
        Resource: ${self:custom.firehose.arn}

          
resources:
  Resources:
    FirehoseStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:custom.firehose.name}
        ShardCount: 5